name: Java Package Build

# Trigger the workflow on push or pull request events to the main branch
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest  # Run the job on the latest Ubuntu image

    steps:
      # Step 1: Check out the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up JDK (e.g., OpenJDK 11)
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adoptopenjdk'  # Can be 'adoptopenjdk', 'zulu', or 'openjdk'

      # Step 3: Cache Maven dependencies to speed up the build
      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Step 4: Build the Java project with Maven
      - name: Build with Maven
        run: mvn clean install -DskipTests=true

      # Step 5: Run tests (if you want to run tests as part of the workflow)
      - name: Run tests
        run: mvn test

      # Step 6: Optionally deploy the package (if you have a deployment step, e.g., to Maven Central or Artifactory)
      - name: Deploy to Maven Repository (optional)
        run: mvn deploy
        env:
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}

